In [1]:
import pandas as pd
import numpy as np

In [2]:
x = np.array([0.2,1.2,1,1.4,-1.5,0.5,-0.5])
y = x*3+5
print(x)
print(y)

[ 0.2  1.2  1.   1.4 -1.5  0.5 -0.5]
[5.6 8.6 8.  9.2 0.5 6.5 3.5]


In [3]:
i_w = 0.5
i_b = -0.5
eta = 0.2
ypred = i_b+i_w*x
print(ypred)

[-0.4   0.1   0.    0.2  -1.25 -0.25 -0.75]


In [4]:
Loss = np.sum((y-ypred)**2)*(1/2*len(x))
Loss

1119.78125

In [5]:
db = -(1/len(x))*np.sum(y-ypred)
dw = -(1/len(x))*np.sum((y-ypred)*x)

In [6]:
w,b = i_w,i_b
new_w = w-eta*dw
new_b = b-eta*db
print(new_w,new_b)

1.375 0.7642857142857142


In [7]:
i_w = 0.5
i_b = -0.5
eta = 0.2
w,b = i_w,i_b
for epoch in range(1,101):
    ypred = b + w * x
    Loss = np.sum((y - ypred) ** 2) * (1/2 * len(x))
    print("loss: ",Loss)
    if Loss<0.0001:
        break
    db = -(1 / len(x)) * np.sum(y - ypred)
    dw = -(1 / len(x)) * np.sum((y - ypred) * x)
    new_w = w - eta * dw
    new_b = b - eta * db
    print(new_w, new_b)
    w,b = new_w,new_b

loss:  1119.78125
1.375 0.7642857142857142
loss:  616.829453125
1.9871683673469387 1.7182142857142857
loss:  343.19756940030516
2.4108931268221574 2.4411289358600583
loss:  193.42497430784704
2.7000668944127444 2.991615886068305
loss:  110.78553766716391
2.893661251304609 3.413002598650378
loss:  64.7063274837938
3.019794669196723 3.737390053834571
loss:  38.66497890684488
3.098699789329753 3.9886112505204436
loss:  23.69921095567407
3.1448867218589545 4.1844030142604
loss:  14.923105922836488
3.168719222917103 4.338001283971874
loss:  9.655047940234304
3.1775622467482663 4.4593137639572324
loss:  6.4100923559715985
3.1766166978562187 4.5557826349509
loss:  4.3564006344377635
3.169526008771268 4.633019867815882
loss:  3.021117762716849
3.1588163602272123 4.6952756136763085
loss:  2.1305599482543487
3.1462156876132363 4.745783987268973
loss:  1.5228919171970228
3.1328844314801563 4.787018730343451
loss:  1.100054929706014
3.119582084562092 4.820882578777494
loss:  0.8010414151742614
3.1

In [10]:
df=pd.read_csv("pizza.csv")

In [18]:
x=df.Promote
y=df.Sales

In [19]:
i_w = 0.5
i_b = -0.5
eta = 0.5
w,b = i_w,i_b
for epoch in range(0,101):
    ypred = b + w * x
    Loss = np.sum((y - ypred) ** 2) * (1/2 * len(x))
    print("loss: ",Loss)
    if Loss<0.0001 :
        break
    db = -(1 / len(x)) * np.sum(y - ypred)
    dw = -(1 / len(x)) * np.sum((y - ypred) * x)
    new_w = w - eta * dw
    new_b = b - eta * db
    print(new_w, new_b)
    w,b = new_w,new_b

loss:  316479071.75
37866.44736842105 595.2105263157895
loss:  847846917079612.1
-62008878.03254847 -974653.3150969528
loss:  2.2764472819524064e+21
101607113725.2804 1597057797.312582
loss:  6.112202718932722e+27
-166492314595432.6 -2616921584625.8833
loss:  1.6411107945925033e+34
2.7281250110823926e+17 4288059328390625.0
loss:  4.406340502721931e+40
-4.470276056992499e+20 -7.026367512045442e+18
loss:  1.1830911532544527e+47
7.324945867415342e+23 1.1513329605179915e+22
loss:  3.1765694821912007e+53
-1.2002576860244926e+27 -1.886561703045957e+25
loss:  8.529007800820092e+59
1.9667292276785133e+30 3.0912995470905255e+28
loss:  2.290016776723269e+66
-3.222661183546872e+33 -5.065369913113994e+31
loss:  6.148636465275345e+72
5.280617666011204e+36 8.300060206339199e+34
loss:  1.650893162285433e+79
-8.652762839902196e+39 -1.360038864101517e+38
loss:  4.432605909737657e+85
1.4178323351356503e+43 2.228544933269068e+41
loss:  1.1901433478494315e+92
-2.3232446881427913e+46 -3.651669559369685e+44

C:\Users\dbda\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
C:\Users\dbda\AppData\Local\Temp\ipykernel_11052\2667197451.py:13: RuntimeWarning: invalid value encountered in scalar subtract
  new_w = w - eta * dw
